pipeline {
    agent any

    environment {
        JAVA_HOME = "/var/jenkins_home/java-21-openjdk"
        PATH = "${JAVA_HOME}/bin:${PATH}"
        GIT_REPO = 'https://lab.ssafy.com/s12-webmobile2-sub1/S12P11A309.git'
        BRANCH = 'BackEnd'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                sh 'rm -rf ${WORKSPACE}/*'  // 기존 워크스페이스 삭제
            }
        }

        stage('git clone repository') {
            steps {
                sh 'echo $JAVA_HOME'
                sh 'java -version'
                git branch: "${BRANCH}", url: "${GIT_REPO}", credentialsId: 'gitlab-token'
            }
        }
        stage('build') {
            steps {
                dir("${WORKSPACE}/opt-back") {
                    sh "chmod +x gradlew"
                    sh "./gradlew clean build -x test"
                }
            }
        }

        stage('deploy') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'aws-key', keyFileVariable: 'SSH_KEY')]) {
                    sh '''
                        ssh -i $SSH_KEY -o StrictHostKeyChecking=no ubuntu@172.26.13.75 << 'EOF'

                        rm -rf /home/ubuntu/docker/backend-src #기존에 있는 파일 제거
                        cp -r /home/ubuntu/S12P11A309/opt-back /home/ubuntu/docker/backend-src #파일 복사해서 넣기기
                        sh /home/ubuntu/docker/backend-src/deploy.sh #deploy.sh파일 실행

                    '''
                }
            }
        }
    }
}